### ISSUE TITLE
Hilfe?

### ISSUE THREAD

**Issue by uweschaefer** [SteppXXL/Datenstrukturen#1]
Wenn ich irgendwas helfen kann, sagt bescheid.

**Comment by StephanPraetsch** [comment]
Mach, dass ich mehr Zeit habe!

**Comment by uweschaefer** [comment]
Projekt tot?

**Comment by StephanPraetsch** [comment]
Nein. wir müssen nur die verdammten 10% mal nehmen
Am 06.12.2015 22:00 schrieb "Uwe Schaefer" notifications@github.com:

**Comment by uweschaefer** [comment]
On 06.12.2015 22:06, SteppXXL wrote:

> Nein. wir müssen nur die verdammten 10% mal nehmen

Tip: Am Sprintanfang (Am besten am ersten Tag) HomeOffice für 10% 
Projekt nehmen.
Wirkt bei mir Wunder!
